package user;

//imports necessários
import conexao.Conexao;
import controle.frm_login;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author Victor e Mariane
 * Mari Vek Histories
 */

public class frm_catalogo extends javax.swing.JFrame {

    //declarando variavel para a classe Conexao
    Conexao con_cliente;
    
    //variáveis para passagem de dados do usuário e dos filmes entre as classes
    private int id;
    private int id_film;
    private String url;
    private String nome;
    private String usuario;
    private String nasc;
    private String descricao;
    
    /**
     * Creates new form Catalogo
     */
    //método construtor
    public frm_catalogo(int realId, String realUser, String realNome, String realNasc) {
        initComponents(); //iniciando componentes do JFrame
        initVariables(realId, realUser, realNome, realNasc); //iniciando variáveis do parâmetro
        getContentPane().setBackground(Color.black); //colorindo fundo do JFrame
        icone(); //setando ícone do programa
        con_cliente = new Conexao(); //instância do objeto conexão
        con_cliente.conecta(); //conectando ao banco
    }

    //método que inicia as variaveis com os dados do usuário
    private void initVariables(int realId, String realUser, String realNome, String realNasc){
        id = realId;
        nome = realNome;
        nasc = realNasc;
        usuario = realUser;
    }
    
    //método que define o ícone do programa
    private void icone(){
        //método que traz a imagem na raiz do projeto
        //método getClass e getResourse são para puxar a imagem no arquivo .jar 
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/icones/icon.png"));
        //método que redimensiona a imagem
        Image scaleImage = imageIcon.getImage().getScaledInstance(25, 25,Image.SCALE_DEFAULT);
        //método que traz a imagem dimensionada
        ImageIcon img = new ImageIcon(scaleImage);
        
        this.setIconImage(img.getImage());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btn1_2 = new javax.swing.JButton();
        btn1_3 = new javax.swing.JButton();
        btn1_4 = new javax.swing.JButton();
        btn2_1 = new javax.swing.JButton();
        btn2_2 = new javax.swing.JButton();
        btn2_4 = new javax.swing.JButton();
        btn3_3 = new javax.swing.JButton();
        btn3_1 = new javax.swing.JButton();
        btn2_3 = new javax.swing.JButton();
        btn3_2 = new javax.swing.JButton();
        btn3_4 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        btn1_1 = new javax.swing.JButton();
        lblRomance = new javax.swing.JLabel();
        lblTerror = new javax.swing.JLabel();
        lblAcao = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        welcome1 = new javax.swing.JLabel();
        lblLoc = new javax.swing.JLabel();
        lblcount = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Javaflix(Catálogo de Filmes)");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Panel.setBackground(new java.awt.Color(0, 51, 51));
        Panel.setPreferredSize(new java.awt.Dimension(700, 715));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("CATÁLOGO");

        btn1_2.setBackground(new java.awt.Color(0, 0, 0));
        btn1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/catalogo/6.png"))); // NOI18N
        btn1_2.setToolTipText("Titanic");
        btn1_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1_2ActionPerformed1(evt);
            }
        });

        btn1_3.setBackground(new java.awt.Color(0, 0, 0));
        btn1_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/catalogo/7.png"))); // NOI18N
        btn1_3.setToolTipText("O Melhor Amigo da Noiva");
        btn1_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1_3ActionPerformed(evt);
            }
        });

        btn1_4.setBackground(new java.awt.Color(0, 0, 0));
        btn1_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/catalogo/8.png"))); // NOI18N
        btn1_4.setToolTipText("Sociedade Literária");
        btn1_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1_4ActionPerformed(evt);
            }
        });

        btn2_1.setBackground(new java.awt.Color(0, 0, 0));
        btn2_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/catalogo/1.png"))); // NOI18N
        btn2_1.setToolTipText("A Noiva-Cadáver");
        btn2_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2_1ActionPerformed(evt);
            }
        });

        btn2_2.setBackground(new java.awt.Color(0, 0, 0));
        btn2_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/catalogo/2.png"))); // NOI18N
        btn2_2.setToolTipText("Casa Monstro");
        btn2_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2_2ActionPerformed(evt);
            }
        });

        btn2_4.setBackground(new java.awt.Color(0, 0, 0));
        btn2_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/catalogo/4.png"))); // NOI18N
        btn2_4.setToolTipText("Invocação do Mal");
        btn2_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2_4ActionPerformed(evt);
            }
        });

        btn3_3.setBackground(new java.awt.Color(0, 0, 0));
        btn3_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/catalogo/11.png"))); // NOI18N
        btn3_3.setToolTipText("The Batman");
        btn3_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3_3ActionPerformed(evt);
            }
        });

        btn3_1.setBackground(new java.awt.Color(0, 0, 0));
        btn3_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/catalogo/9.png"))); // NOI18N
        btn3_1.setToolTipText("Motoqueiro Fantasma");
        btn3_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3_1ActionPerformed(evt);
            }
        });

        btn2_3.setBackground(new java.awt.Color(0, 0, 0));
        btn2_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/catalogo/3.png"))); // NOI18N
        btn2_3.setToolTipText("Coraline e o Mundo Secreto");
        btn2_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2_3ActionPerformed(evt);
            }
        });

        btn3_2.setBackground(new java.awt.Color(0, 0, 0));
        btn3_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/catalogo/10.png"))); // NOI18N
        btn3_2.setToolTipText("Clube da Luta");
        btn3_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3_2ActionPerformed(evt);
            }
        });

        btn3_4.setBackground(new java.awt.Color(0, 0, 0));
        btn3_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/catalogo/12.png"))); // NOI18N
        btn3_4.setToolTipText("Em Ritmo de Fuga");
        btn3_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3_4ActionPerformed(evt);
            }
        });

        jButton11.setText(";)");

        btn1_1.setBackground(new java.awt.Color(0, 0, 0));
        btn1_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/catalogo/5.png"))); // NOI18N
        btn1_1.setToolTipText("Orgulho e Preconceito");
        btn1_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1_2ActionPerformed(evt);
            }
        });

        lblRomance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRomance.setForeground(new java.awt.Color(255, 255, 255));
        lblRomance.setText("Romance");

        lblTerror.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTerror.setForeground(new java.awt.Color(255, 255, 255));
        lblTerror.setText("Terror");

        lblAcao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAcao.setForeground(new java.awt.Color(255, 255, 255));
        lblAcao.setText("Ação");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(lblRomance)
                        .addGap(184, 184, 184)
                        .addComponent(lblTitulo))
                    .addComponent(lblAcao)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(btn3_1)
                        .addGap(18, 18, 18)
                        .addComponent(btn3_2)
                        .addGap(18, 18, 18)
                        .addComponent(btn3_3)
                        .addGap(18, 18, 18)
                        .addComponent(btn3_4))
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(btn2_1)
                                .addGap(18, 18, 18)
                                .addComponent(btn2_2)
                                .addGap(18, 18, 18)
                                .addComponent(btn2_3)
                                .addGap(18, 18, 18)
                                .addComponent(btn2_4))
                            .addComponent(lblTerror))
                        .addGroup(PanelLayout.createSequentialGroup()
                            .addComponent(btn1_1)
                            .addGap(18, 18, 18)
                            .addComponent(btn1_2)
                            .addGap(18, 18, 18)
                            .addComponent(btn1_3)
                            .addGap(18, 18, 18)
                            .addComponent(btn1_4))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblRomance)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1_2)
                    .addComponent(btn1_3)
                    .addComponent(btn1_4)
                    .addComponent(btn1_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTerror)
                .addGap(1, 1, 1)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn2_2)
                    .addComponent(btn2_1)
                    .addComponent(btn2_3)
                    .addComponent(btn2_4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAcao)
                .addGap(1, 1, 1)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn3_2)
                    .addComponent(btn3_3)
                    .addComponent(btn3_1)
                    .addComponent(btn3_4))
                .addGap(183, 183, 183)
                .addComponent(jButton11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logoLocadora.png"))); // NOI18N

        lbluser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbluser.setForeground(new java.awt.Color(227, 4, 25));
        lbluser.setText("null");

        welcome1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        welcome1.setForeground(new java.awt.Color(227, 4, 25));
        welcome1.setText("Olá,");

        lblLoc.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblLoc.setForeground(new java.awt.Color(227, 4, 25));
        lblLoc.setText("Filmes Alugados");
        lblLoc.setToolTipText("Ver os filmes que aluguei");
        lblLoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLocMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLocMouseExited(evt);
            }
        });

        lblcount.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblcount.setForeground(new java.awt.Color(227, 4, 25));
        lblcount.setText("Minha Conta");
        lblcount.setToolTipText("Ver informações da minha conta");
        lblcount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblcount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcountMouseExited(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(227, 4, 25));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/resultset/door_in.png"))); // NOI18N
        btnExit.setToolTipText("Sair da sua conta");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLoc))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnExit))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblcount)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(welcome1)
                                    .addComponent(lbluser))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(welcome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbluser)
                .addGap(67, 67, 67)
                .addComponent(lblLoc)
                .addGap(18, 18, 18)
                .addComponent(lblcount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2_1ActionPerformed
        //botão para alugar o filme Noiva Cadaver
        
        //passando dados do filme e chamando a classe de aluguel
        id_film = 12;
        url = "/icones/aluguel/noivaCadaver.png";
        descricao = "As famílias de Victor e Victoria estão arranjando seu casamento. Nervoso com \n" +
                    "a cerimônia, Victor vai sozinho à floresta para ensaiar seus votos. No entanto, \n" +
                    "o que ele pensava ser um tronco de árvore na verdade é o braço esquelético de \n" +
                    "Emily, uma noiva que foi assassinada depois de fugir com seu amor. Convencida \n" +
                    "que Victor acabara de lhe pedir a mão em casamento, Emily o leva para o mundo \n" +
                    "dos mortos, mas ele precisa retornar rapidamente antes que Victoria se case \n" +
                    "com o malvado Lorde Barkis.";
        frm_selected_film mostra = new frm_selected_film(id, id_film, url, usuario, nome, nasc, descricao);
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn2_1ActionPerformed

    private void btn1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1_4ActionPerformed
        //botão para alugar o filme Sociedade Literária
        
        //passando dados do filme e chamando a classe de aluguel
        id_film = 9;
        url = "/icones/aluguel/sociedadeLiteraria.png";
        descricao = "Em 1946, uma escritora londrina começa a trocar cartas com moradores na ilha \n" +
                    "de Guernsey, ocupada pelos alemães durante a Segunda Guerra Mundial. Sentindo-se \n" +
                    "obrigada a visitar a ilha, ela começa a ter uma ideia de como era durante a ocupação.";
        frm_selected_film mostra = new frm_selected_film(id, id_film, url, usuario, nome, nasc, descricao);
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn1_4ActionPerformed

    private void btn1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1_2ActionPerformed
        //botão para alugar o filme Orgulho e Preconceito
        
        //passando dados do filme e chamando a classe de aluguel
        id_film = 1;
        url = "/icones/aluguel/orgulhoPreconceito.png";
        descricao = "Elizabeth Bennet vive com sua mãe, pai e irmãs no campo, na Inglaterra.\n" +
                    " Por ser uma das filhas mais velhas, ela enfrenta uma crescente pressão \n" +
                    "de seus pais para se casar. Quando Elizabeth é apresentada ao belo e rico \n" +
                    "Darcy, faíscas voam. Embora haja uma química óbvia entre os dois, a \n" +
                    "natureza excessivamente reservada de Darcy ameaça a relação.";
        frm_selected_film mostra = new frm_selected_film(id, id_film, url, usuario, nome, nasc, descricao);
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn1_2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //quando a janela for aberta, o nome do usuário aparecerá nas boas vindas
        
        lbluser.setText(nome + "!");
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //quando a janela for ativada, o nome do usuário aparecerá nas boas vindas
        
        lbluser.setText(nome + "!");
    }//GEN-LAST:event_formWindowActivated

    private void lblLocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLocMouseClicked
        //quando clicarem na label de "Filmes Alugados", chamará a classe para exibir
        //os filmes alugados pelo usuário
        
        //checando se o usuário possui alguma locação em seu nome
        try{
            con_cliente.executaSQL("select * from locacao where id_usuario = '" + id + "'");
        
            if(con_cliente.resultset.first()){
                frm_view_loc mostra = new frm_view_loc(id, usuario, nome, nasc);
                mostra.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "\n Voce não possui nenhum filme alugado!\n Alugue no nosso catálogo", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "\n Erro no cadastro :\n ", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_lblLocMouseClicked

    private void lblLocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLocMouseEntered
        //quando o mouse estiver sobre a label, ela ficara decorada
        
        lblLoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLoc.setFont(new java.awt.Font("Tahoma", 1, 19));
        lblLoc.setText("<html><u>Filmes Alugados</u></html>");
    }//GEN-LAST:event_lblLocMouseEntered

    private void lblLocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLocMouseExited
        //quando o mouse não estiver mais sobre a label, ela voltará ao normal
        
        lblLoc.setFont(new java.awt.Font("Tahoma", 0, 22));
    }//GEN-LAST:event_lblLocMouseExited

    private void lblcountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcountMouseEntered
        //quando o mouse estiver sobre a label, ela ficara decorada
        
        lblcount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblcount.setFont(new java.awt.Font("Tahoma", 1, 19));
        lblcount.setText("<html><u>Minha Conta</u></html>");
    }//GEN-LAST:event_lblcountMouseEntered

    private void lblcountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcountMouseClicked
        //quando clicar na label "Minha Conta", chamará a classe para exibir
        //dados do usuário
        
        frm_user_count mostra = new frm_user_count(id, usuario, nome, nasc);
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblcountMouseClicked

    private void lblcountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcountMouseExited
        //quando o mouse não estiver mais sobre a label, ela voltará ao normal
        
        lblcount.setFont(new java.awt.Font("Tahoma", 0, 22));
    }//GEN-LAST:event_lblcountMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //botão que sai da conta do usuário e retorna para a tela de login
        
        //mostra mensagem de confirmação
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja sair da sua conta? ","Logout", JOptionPane.YES_NO_OPTION, 3);
            
        //se confirmar, volta a tela de login
        if (resposta == 0){
            frm_login mostra = new frm_login();
            mostra.setVisible(true);
            dispose();
        }
        else{
            
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btn1_2ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1_2ActionPerformed1
        //botão para alugar o filme Titanic
        
        //passando dados do filme e chamando a classe de aluguel
        id_film = 4;
        url = "/icones/aluguel/titanic.png";
        descricao = "Um artista pobre e uma jovem rica se conhecem e se apaixonam na fatídica \n" +
                    "jornada do Titanic, em 1912. Embora esteja noiva do arrogante herdeiro de \n" +
                    "uma siderúrgica, a jovem desafia sua família e amigos em busca do verdadeiro amor.";
        frm_selected_film mostra = new frm_selected_film(id, id_film, url, usuario, nome, nasc, descricao);
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn1_2ActionPerformed1

    private void btn1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1_3ActionPerformed
        //botão para alugar o filme O Melhor Amigo da Noiva
        
        //passando dados do filme e chamando a classe de aluguel
        id_film = 6;
        url = "/icones/aluguel/oMelhorAmigoDaNoiva.png";
        descricao = "Tom é um jovem que evita compromissos sérios e tem várias namoradas. Hannah, \n" +
                    "sua melhor amiga, encontra o homem ideal justamente quando Tom descobre que \n" +
                    "realmente a ama. No entanto, Hannah pede para ele participar de sua festa de \n" +
                    "despedida, e Tom aproveita essa oportunidade para tentar evitar que o casamento \n" +
                    "aconteça.";
        frm_selected_film mostra = new frm_selected_film(id, id_film, url, usuario, nome, nasc, descricao);
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn1_3ActionPerformed

    private void btn2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2_2ActionPerformed
        //botão para alugar o filme A Casa Monstro
        
        //passando dados do filme e chamando a classe de aluguel
        id_film = 7;
        url = "/icones/aluguel/aCasaMonstro.png";
        descricao = "Nenhum adulto acredita quando três adolescentes falam que existe uma casa no \n" +
                    "bairro que é uma criatura perigosa. Com o Dia das Bruxas se aproximando, \n" +
                    "eles têm que descobrir uma forma de destruir a casa antes que ela faça mal \n" +
                    "a crianças inocentes.";
        frm_selected_film mostra = new frm_selected_film(id, id_film, url, usuario, nome, nasc, descricao);
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn2_2ActionPerformed

    private void btn2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2_3ActionPerformed
        //botão para alugar o filme Coraline
        
        //passando dados do filme e chamando a classe de aluguel
        id_film = 3;
        url = "/icones/aluguel/coraline.png";
        descricao = "Enquanto explora sua nova casa à noite, a pequena Coraline descobre uma \n" +
                    "porta secreta que contém um mundo parecido com o dela, porém melhor em \n" +
                    "muitas maneiras. Todos têm botões no lugar dos olhos, os pais são carinhosos \n" +
                    "e os sonhos de Coraline viram realidade por lá. Ela se encanta com essa descoberta, \n" +
                    "mas logo percebe que segredos estranhos estão em ação: uma outra mãe e o resto de \n" +
                    "sua família tentam mantê-la eternamente nesse mundo paralelo.";
        frm_selected_film mostra = new frm_selected_film(id, id_film, url, usuario, nome, nasc, descricao);
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn2_3ActionPerformed

    private void btn2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2_4ActionPerformed
        //botão para alugar o filme Invocação do Mal
        
        //passando dados do filme e chamando a classe de aluguel
        id_film = 10;
        url = "/icones/aluguel/invocacaoDoMal.png";
        descricao = "Os investigadores paranormais Ed e Lorraine Warren trabalham para ajudar \n" +
                    "a família aterrorizada por uma entidade demoníaca em sua fazenda.";
        frm_selected_film mostra = new frm_selected_film(id, id_film, url, usuario, nome, nasc, descricao);
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn2_4ActionPerformed

    private void btn3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3_1ActionPerformed
        //botão para alugar o filme Motoqueiro Fantasma
        
        //passando dados do filme e chamando a classe de aluguel
        id_film = 2;
        url = "/icones/aluguel/motoqueiroFantasma.png";
        descricao = "Johnny Blaze trabalha como dublê e piloto de motocicleta. Há muito tempo, ele fez \n" +
                    "um pacto com Mefisto para proteger as duas pessoas que mais amava: seu pai, \n" +
                    "Barton, e sua namorada de adolescência, Roxanne Simpson. Em troca, Johnny se \n" +
                    "transforma no Motoqueiro Fantasma, o justiceiro de alguns demônios bastante \n" +
                    "cruéis. Forçado a obedecer Mefisto, Johnny decide enfrentá-lo de forma a usar \n" +
                    "sua maldição para proteger pessoas inocentes.";
        frm_selected_film mostra = new frm_selected_film(id, id_film, url, usuario, nome, nasc, descricao);
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn3_1ActionPerformed

    private void btn3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3_2ActionPerformed
        //botão para alugar o filme Clube da Luta
        
        //passando dados do filme e chamando a classe de aluguel
        id_film = 5;
        url = "/icones/aluguel/clubeDaLuta.png";
        descricao = "Um homem deprimido que sofre de insônia conhece um estranho vendedor chamado \n" +
                    "Tyler Durden e se vê morando em uma casa suja depois que seu perfeito apartamento \n" +
                    "é destruído. A dupla forma um clube com regras rígidas onde homens lutam. A parceria \n" +
                    "perfeita é comprometida quando uma mulher, Marla, atrai a atenção de Tyler.";
        frm_selected_film mostra = new frm_selected_film(id, id_film, url, usuario, nome, nasc, descricao);
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn3_2ActionPerformed

    private void btn3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3_3ActionPerformed
        //botão para alugar o filme Batman
        
        //passando dados do filme e chamando a classe de aluguel
        id_film = 8;
        url = "/icones/aluguel/batman.png";
        descricao = "Após dois anos espreitando as ruas como Batman, Bruce Wayne se encontra nas \n" +
                    "profundezas mais sombrias de Gotham City. Com poucos aliados confiáveis, o \n" +
                    "vigilante solitário se estabelece como a personificação da vingança para a população.";
        frm_selected_film mostra = new frm_selected_film(id, id_film, url, usuario, nome, nasc, descricao);
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn3_3ActionPerformed

    private void btn3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3_4ActionPerformed
        //botão para alugar o filme Em Ritmo de Fuga
        
        //passando dados do filme e chamando a classe de aluguel
        id_film = 11;
        url = "/icones/aluguel/emRitmoDeFuga.png";
        descricao = "O talentoso motorista de fuga Baby confia nas batidas de sua própria trilha \n" +
                    "sonora para ser o melhor que existe. A música silencia um zumbido que o perturba \n" +
                    "desde um acidente na infância. Após conhecer a mulher dos seus sonhos, ele reconhece \n" +
                    "uma oportunidade de se livrar do estilo de vida questionável e recomeçar do zero. \n" +
                    "Obrigado a trabalhar para um chefão do crime, Baby lida com a música ao mesmo tempo \n" +
                    "em que um golpe fadado ao fracasso ameaça sua vida, seu amor e sua liberdade.";
        frm_selected_film mostra = new frm_selected_film(id, id_film, url, usuario, nome, nasc, descricao);
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn3_4ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btn1_1;
    private javax.swing.JButton btn1_2;
    private javax.swing.JButton btn1_3;
    private javax.swing.JButton btn1_4;
    private javax.swing.JButton btn2_1;
    private javax.swing.JButton btn2_2;
    private javax.swing.JButton btn2_3;
    private javax.swing.JButton btn2_4;
    private javax.swing.JButton btn3_1;
    private javax.swing.JButton btn3_2;
    private javax.swing.JButton btn3_3;
    private javax.swing.JButton btn3_4;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton jButton11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAcao;
    private javax.swing.JLabel lblLoc;
    private javax.swing.JLabel lblRomance;
    private javax.swing.JLabel lblTerror;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblcount;
    private javax.swing.JLabel lbluser;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel welcome1;
    // End of variables declaration//GEN-END:variables
}
