package controle;

//imports necessários para funcionamento do projeto
import conexao.Conexao;
import java.awt.Color;
import java.awt.Image;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor e Mariane
 * Mari Vek Histories
 */

public class frm_cadastro extends javax.swing.JFrame {

    //criando objeto da classe conexao
    Conexao con_cliente;
    
    /**
     * Creates new form Cadastro
     */
    //método construtor
    public frm_cadastro() {
        initComponents(); //método inicializador dod componentes  
        con_cliente = new Conexao(); //instância do objeto conexão
        con_cliente.conecta(); //conectando ao banco
        con_cliente.executaSQL("select * from usuarios order by id"); //retornando todos os registros do banco
        btnCadastrar.setBackground(Color.RED); //colorindo os botões
        btnReturn.setBackground(Color.RED);
        logo(); //chamando metodo para setar logo "Javaflix"
        icone(); //chamando metodo para setar ícone da janela
        getRootPane().setDefaultButton(btnCadastrar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblNasc = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        txtNasc = new javax.swing.JFormattedTextField();
        alert = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        lblTel = new javax.swing.JLabel();
        txtTel = new javax.swing.JFormattedTextField();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Javaflix(Cadastro)");
        setResizable(false);

        Panel.setBackground(new java.awt.Color(0, 51, 51));

        title.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Cadastro");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome:");

        lblNasc.setForeground(new java.awt.Color(255, 255, 255));
        lblNasc.setText("Data de Nascimento:");

        lblEndereco.setForeground(new java.awt.Color(255, 255, 255));
        lblEndereco.setText("Endereço:");

        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Usuário:");

        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha:");

        btnCadastrar.setBackground(new java.awt.Color(204, 0, 0));
        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setToolTipText("Cadastrar sua conta");
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        txtNome.setToolTipText("Insira seu nome");

        txtEndereco.setToolTipText("Insira seu endereço");

        txtUser.setToolTipText("Insira um usuário único para entrar na sua conta");

        txtSenha.setToolTipText("Insira uma senha numérica de 4 a 8 digitos");

        try {
            txtNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNasc.setToolTipText("Insira sua data de nascimento");

        alert.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        alert.setForeground(new java.awt.Color(255, 0, 0));
        alert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alert.setToolTipText("aviso");
        alert.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnReturn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/resultset/door_in.png"))); // NOI18N
        btnReturn.setToolTipText("Retornar para a tela de Login");
        btnReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        lblTel.setForeground(new java.awt.Color(255, 255, 255));
        lblTel.setText("Telefone:");

        try {
            txtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTel.setToolTipText("Insira seu telefone");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(btnReturn)
                        .addGap(64, 64, 64)
                        .addComponent(btnCadastrar))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNasc)
                            .addComponent(lblNome)
                            .addComponent(lblEndereco)
                            .addComponent(lblTel)
                            .addComponent(lblUser))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEndereco)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblSenha))
                .addContainerGap(49, Short.MAX_VALUE))
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(alert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNasc)
                    .addComponent(txtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTel)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alert, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCadastrar)
                    .addComponent(btnReturn))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //
    private void logo(){
        //classe que traz a imagem na raiz do projeto
        //função getClass e getResourse são para puxar a imagem no arquivo .jar 
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/icones/javaflix.png"));
        //classe que redimensiona a imagem
        Image scaleImage = imageIcon.getImage().getScaledInstance(100, 50,Image.SCALE_DEFAULT);
        //classe que traz a imagem dimensionada
        ImageIcon img = new ImageIcon(scaleImage);
        
        //função que seta a imagem
        logo.setIcon(img);
    }
    
    //método que seta o ícone do programa
    private void icone(){
        //classe que traz a imagem na raiz do projeto
        //função getClass e getResourse são para puxar a imagem no arquivo .jar 
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/icones/icon.png"));
        //classe que redimensiona a imagem
        Image scaleImage = imageIcon.getImage().getScaledInstance(25, 25,Image.SCALE_DEFAULT);
        //classe que traz a imagem dimensionada
        ImageIcon img = new ImageIcon(scaleImage);
        
        //função que seta a imagem
        this.setIconImage(img.getImage());
    }
    
    //método que insere um registro no banco
    private void insert(){
        //adicionando os valores dos campos as variaveis
            DateTimeFormatter formatBra = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            DateTimeFormatter formatSql = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDate nascimento = LocalDate.parse(txtNasc.getText(), formatBra);
            String data_nasc = nascimento.format(formatSql);
            
            String nome = txtNome.getText();
            String endereco = txtEndereco.getText();
            String telefone = txtTel.getText();
            String usuario = txtUser.getText();
            String senha = txtSenha.getText();

            //inserindo o novo registro ao banco
            try {
                //enviando instrução SQL para inserir o cadastro dentro do banco
                String insert_sql="insert into usuarios  (`nome`, `data_nasc`, `endereco`, `telefone`, `usuario`, `senha`) values ('" + nome + "','" + data_nasc + "','" + endereco + "','" + telefone + "','" + usuario + "','" + senha + "');";
                con_cliente.statement.executeUpdate(insert_sql);
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!\n\nAgora entre na sua conta como Usuário", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);

                //chamando a tela login
                frm_login mostra = new frm_login();
                mostra.setVisible(true);
                dispose();

            }catch(SQLException errosql){
                JOptionPane.showMessageDialog(null, "\n Erro no cadastro :\n ", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            }
    }
    
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        //este botão irá cadastrar os dados inseridos pelo usuário no banco, adicionando mais...
        //um registro á tabela
        //INSERT
        
        //tratamento de campos vázios
        if(txtNome.getText().length() > 0 && txtNasc.getValue() != null && txtTel.getValue() != null
            && txtEndereco.getText().length() > 0 && txtUser.getText().length() > 0
            && txtSenha.getText().length() > 0){
            try{
                //checando se o usuário está disponível
                String pesquisa = "select * from usuarios where usuario = '" + txtUser.getText() + "'";
                con_cliente.executaSQL(pesquisa);
                

                if(con_cliente.resultset.first()){
                    JOptionPane.showMessageDialog(null, "Este usuário já está sendo utilizado!\n\nEscolha um Usuário diferente!" ,"Informação",JOptionPane.INFORMATION_MESSAGE);
                }else{
                    //checando se a senha contém apenas números
                    try{
                        long teste;
                        teste =  Long.parseLong(txtSenha.getText());
                        
                        //checando se a senha contém de 4 a 8 digitos
                        if(txtSenha.getText().length() < 4 || txtSenha.getText().length() > 8){
                            JOptionPane.showMessageDialog(null, "A senha deve ter de 4 a 8 digitos!\n\nTente novamente!" ,"Informação",JOptionPane.INFORMATION_MESSAGE);
                        }else{
                            //chamando método para inserir registro no banco
                            insert();
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, "A senha só pode conter números!" ,"Informação",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "\n Erro ao buscar email no banco :\n ", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            }
            
            //restartando instrução construtora
            con_cliente.executaSQL("select * from usuarios order by id");
            
            
        }else{
            alert.setText("Preencha os campos!");
        }    
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        //este botão irá retornar para a tela de login
        
        frm_login mostra = new frm_login();
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReturnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel alert;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNasc;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JFormattedTextField txtNasc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JFormattedTextField txtTel;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
